name: fast_noise
description: A port of the fast noise algorithms.
version: 0.1.2
homepage: https://github.com/frankpepermans/fast_noise
author: Frank <frank@igindo.com>

environment:
  sdk: '>=2.0.0-dev <3.0.0'

dependencies:
  fixnum: ^0.10.0

dev_dependencies:
  test: ^0.12.0
  benchmark_harness: ^1.0.0

web:
  compiler:
    debug: dartdevc
