name: fast_noise
description: A port of the fast noise algorithms, featuring cellular_noise, cubic_noise, perlin_noise, simplex_noise, value_noise and white_noise
version: 0.1.3+1
homepage: https://github.com/frankpepermans/fast_noise
author: Frank <frank@igindo.com>

environment:
  sdk: '>=2.0.0-dev <3.0.0'

dependencies:
  fixnum: ^0.10.0

dev_dependencies:
  benchmark_harness: ^1.0.0
  build_runner: ^1.7.1
  build_web_compilers: ^2.7.0
  pedantic: ^1.9.0
  test: ^1.3.0
