name: fast_noise
description: A port of the fast noise algorithms.
version: 0.1.2+3
homepage: https://github.com/frankpepermans/fast_noise
author: Frank <frank@igindo.com>

environment:
  sdk: '>=2.0.0-dev <3.0.0'

dependencies:
  fixnum: ^0.10.0

dev_dependencies:
  benchmark_harness: ^1.0.0
  build_runner: ^0.9.2
  build_web_compilers: ^0.4.1
  test: ^1.3.0

web:
  compiler:
    debug: dartdevc
